name: build-app
description: Build and Push Docker Image
inputs:
  dockerfile:
    required: true
    description: Dockerfile path
  push:
    required: true
    description: Push image to registry
  image:
    required: true
    description: Image name
  platforms:
    required: true
    description: Image platforms

runs:
  using: composite
  
  steps:
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.image }}
        flavor: |
          latest=false
        tags: |
          type=raw,value=rn-${{ github.run_number }}-a${{ github.run_attempt }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        cache-from: |
          type=gha
        cache-to: |
          type=gha