inputs:
  image:
    required: true
    description: Image name
  run-tag:
    required: true
    description: Tag for this run
  latest:
    required: false
    description: Tag image as latest
    default: false

runs:
  using: composite

  steps:
    
    - name: Extract metadata (tags, labels) for Promotion
      id: remeta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        flavor: |
          latest=false
        tags: |
          type=raw,value={{branch}},enable=${{ github.ref_type == 'branch' && github.event_name != 'pull_request' }}
          type=raw,value=latest,enable=${{ inputs.latest }}
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          
    # Point those tags at the built digest without rebuilding
    - name: Promote by retagging digest (no rebuild)
      shell: bash
      run: |
        set -euo pipefail

        # lower-case the repo right here
        IMG='${{ inputs.image }}'           # e.g. ghcr.io/OpenShock/api
        IMG_LC="${IMG,,}"                   # bash lowercase; POSIX alt below
        
        # metadata-action outputs newline-separated tags
        mapfile -t TAGS <<< "${{ steps.remeta.outputs.tags }}"
        ARGS=()
        for t in "${TAGS[@]}"; do
          [[ -n "$t" ]] && ARGS+=( --tag "$t" )
        done
        
        # Create/overwrite manifest tags pointing at the original digest
        docker buildx imagetools create "${ARGS[@]}" "${IMG_LC}:${{ inputs.run-tag }}"