// <auto-generated />
// DO NOT EDIT - manual changes are overwritten on the next regeneration.
// 
// Cloudflare public proxy IP ranges (https://www.cloudflare.com/ips), baked in as a startup fallback for TrustedProxiesFetcher when the live fetch at application start fails or times out.
// Regenerated by the FetchCloudflareIPs target in Common.csproj, gated on -p:UpdateCloudflareIPs=true. The Update Cloudflare Proxies GitHub workflow is the only caller that passes that flag.
// 
// Generated: 2026-04-24T17:08:34Z
// IPv4 SHA256: f02c6d83bc01ab0ae8577160e036d700c7455359bce054df884e5d7d9e4e9e7b
// IPv6 SHA256: 9e9d39e3e83bad00c4decafd53c63fa62029f3d95db68de937d2be28234ca0a9
using System.Net;

namespace OpenShock.Common.Utils;

public static partial class TrustedProxiesFetcher
{
    private static readonly IPNetwork[] CloudflareNetworks =
    [
        // 173.245.48.0/20
        new IPNetwork(new IPAddress(0x0030f5adL), prefixLength: 20),

        // 103.21.244.0/22
        new IPNetwork(new IPAddress(0x00f41567L), prefixLength: 22),

        // 103.22.200.0/22
        new IPNetwork(new IPAddress(0x00c81667L), prefixLength: 22),

        // 103.31.4.0/22
        new IPNetwork(new IPAddress(0x00041f67L), prefixLength: 22),

        // 141.101.64.0/18
        new IPNetwork(new IPAddress(0x0040658dL), prefixLength: 18),

        // 108.162.192.0/18
        new IPNetwork(new IPAddress(0x00c0a26cL), prefixLength: 18),

        // 190.93.240.0/20
        new IPNetwork(new IPAddress(0x00f05dbeL), prefixLength: 20),

        // 188.114.96.0/20
        new IPNetwork(new IPAddress(0x006072bcL), prefixLength: 20),

        // 197.234.240.0/22
        new IPNetwork(new IPAddress(0x00f0eac5L), prefixLength: 22),

        // 198.41.128.0/17
        new IPNetwork(new IPAddress(0x008029c6L), prefixLength: 17),

        // 162.158.0.0/15
        new IPNetwork(new IPAddress(0x00009ea2L), prefixLength: 15),

        // 104.16.0.0/13
        new IPNetwork(new IPAddress(0x00001068L), prefixLength: 13),

        // 104.24.0.0/14
        new IPNetwork(new IPAddress(0x00001868L), prefixLength: 14),

        // 172.64.0.0/13
        new IPNetwork(new IPAddress(0x000040acL), prefixLength: 13),

        // 131.0.72.0/22
        new IPNetwork(new IPAddress(0x00480083L), prefixLength: 22),

        // 2400:cb00::/32
        new IPNetwork(new IPAddress([0x24, 0x00, 0xcb, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]), prefixLength: 32),

        // 2606:4700::/32
        new IPNetwork(new IPAddress([0x26, 0x06, 0x47, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]), prefixLength: 32),

        // 2803:f800::/32
        new IPNetwork(new IPAddress([0x28, 0x03, 0xf8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]), prefixLength: 32),

        // 2405:b500::/32
        new IPNetwork(new IPAddress([0x24, 0x05, 0xb5, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]), prefixLength: 32),

        // 2405:8100::/32
        new IPNetwork(new IPAddress([0x24, 0x05, 0x81, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]), prefixLength: 32),

        // 2a06:98c0::/29
        new IPNetwork(new IPAddress([0x2a, 0x06, 0x98, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]), prefixLength: 29),

        // 2c0f:f248::/32
        new IPNetwork(new IPAddress([0x2c, 0x0f, 0xf2, 0x48, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]), prefixLength: 32),

    ];
}
