on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

name: ci-tag

env:
  DOTNET_VERSION: 10.0.x
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/api

jobs:

  # Pre-job to find the latest tag
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.latest-tag.outputs.tag }}
    steps:
      - name: Find latest tag
        id: latest-tag
        uses: OpenShock/actions/find-latest-tag@d8af907a3bbfcb1d4eb1dc6272501524d7c465d6 # v1.0.0
        with:
          regex: '^[0-9]+\.[0-9]+\.[0-9]+$'

  # Delegate building and containerizing to a single workflow.
  build-and-containerize:
    needs: get-latest-tag
    uses: ./.github/workflows/ci-build.yml
    with:
      platforms: linux/amd64,linux/arm64
      latest: ${{ needs.get-latest-tag.outputs.latest-tag == github.ref_name }}
      push: true
      tag-prefix: 'tag'